#include "tracking.h"

const float SENSOR_SPACING_INCHES = 7.0f;
const int SAMPLES_PER_SECOND = 16000;

const float SPEED_OF_SOUND_SECONDS_PER_METER = (float)(1.0/340.29);
const float METERS_PER_INCH = 0.0254f;
const float SPEED_OF_SOUND_SECONDS_PER_INCH = METERS_PER_INCH *
  SPEED_OF_SOUND_SECONDS_PER_METER;

const float SENSOR_SPACING_SAMPLES = SENSOR_SPACING_INCHES *
  SAMPLES_PER_SECOND * SPEED_OF_SOUND_SECONDS_PER_INCH;
